Update readme.md
Got an error about TypeError: puppeteer.use(...) is not a function because lines didn't have `;`, but it works when I added, so help the next person!